cache:
  paths:
    - alpine-target
    - .cargo

stages:
  - test

.alpine_before: &alpine_before
  - apk add libc-dev openssl-dev
  - rustup component add rustfmt
  - export CARGO_HOME="${PWD}/.cargo"

test:
  stage: test
  image: rust:1-alpine
  before_script:
    - *alpine_before
  script:
    - cargo test --verbose
