cache:
  paths:
    - alpine-target

stages:
  - build-test
  - downstream

.alpine_before: &alpine_before
  - apk add libc-dev openssl-dev
  - rustup component add rustfmt

build-test:
  stage: build-test
  image: rust:1-alpine
  # tags:
  #   - avassa-docker
  before_script:
    - *alpine_before
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-client-utilities:
  stage: downstream
  trigger:
    project: avassa-public/avassa-client-rust-utilities
