[package]
name = "avassa-client"
version = "0.1.0"
authors = ["Fredrik Jansson <fj@avassa.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-core = "0.3"
futures-util = "0.3"
reqwest = { version="0.10", features = ["json"] }
serde = { version = "1", features=["derive"] }
serde_json = { version = "1" }
thiserror = "1"
tracing = "0.1"
tracing-futures = "0.2"
tokio = { version="0.2", features = ["macros", "sync", "time"] }
tokio-tungstenite = "0.11"
tungstenite = "*"
url = "2"
