[workspace]
members = [
  "avassa-client",
  "avassa-client-utilities",
  # "elasticsearch",
  "examples-common",
  "hvac-common",
  "temperature-collector",
  "temperature-aggregator",
  "stats-aggregator",
  "lua-runner",
]
