name: high-resource
services:
  - name: lua-runner
    containers:
      - name: lua-runner
        image: "fredrikjanssonse/runner"
        env:
          - name: RUST_LOG
            value: "debug"
          - name: SCRIPT
            value: |
              while true do
                      local start_time = os.clock()

                      print("High CPU")
                      local s = 0
                      while (os.clock() - start_time) < 10 do
                              s=s+1
                      end

                      print("Consuming mem ")
                      local t = {}
                      for i=1,(17600000/2) do t[#t+1]=i end

                      print("Sleeping")
                      avassa:sleep(10)
              end
    mode: replicated
    replicas: 1
