name: temp-aggregator
services:
  - name: aggregator
    containers:
      - name: aggregator
        image: "temperature"
        cmd: ["temperature-aggregator"]
        env:
          - name: RUST_LOG
            value: "debug"
          - name: SUPD
            value: "https://api:4646"
    placement:
      match-host-labels: >
        name = topdc-1
    network:
      ingress-ip-per-instance:
        ip-versions:
          - ipv4
        protocols:
          - name: tcp
            port-ranges: "9000"
    mode: replicated
    replicas: 1

